version: "3"

services:
  mongo:
    container_name: mongodatabase
    restart: always
    image: mongo
    networks:
      - red_privada
    volumes:
      - mongo-data:/data/db
    expose:
      - ${PORT}
  server:
    depends_on:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: servidor
    restart: always
    expose:
      - ${BACKENDPORT}
    links:
      - mongo
    networks:
      - red-proxy
      - red_privada
    environment:
      VIRTUAL_HOST: localhost3
  react-app:
    depends_on:
      - server
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: react-application-gestion
    stdin_open: true
    networks:
      - red-proxy
    environment:
      VIRTUAL_HOST: localhost2
networks:
  red-proxy:
    external:
      name: nginx-proxy
  red_privada:

volumes:
  mongo-data:
    driver: local
